### ISSUE TITLE
Fix training data wordlist running out when the cipher charset has a limited amount of characters

### ISSUE THREAD

**Issue by mklarz** [corax/cipher_identifier#24]
Looks like the wordlist is running out of words, perhaps randomize the cases if the charset contains upper- and lowercase characters?

```bash
$ python scripts/generate_train_data.py babylonian-numbers
Generating 10000 training images for cipher: babylonian-numbers
Cipher image count: 15
Cipher charset: 0123456789ABCDE
Traceback (most recent call last):
  File "scripts/generate_train_data.py", line 534, in <module>
    generate_train_data(cipher, wordlist, limit=limit)
  File "scripts/generate_train_data.py", line 434, in generate_train_data
    sentences = generate_sentences(
  File "scripts/generate_train_data.py", line 163, in generate_sentences
    word = wordlist.pop()
IndexError: pop from an empty deque
```

**Comment by mklarz** [comment]
The wordlist is indeed running out of words, this is due to the charset only containing "ABCDE" and it's difficult to create ~10000 words out of those 5 characters.

We need to create a larger wordlist, or generate random words out of the charset.
